import { create } from 'zustand';

// Create a custom hook called useStore using Zustand library
const useStore = create((set) => ({
  // Define initial state variables
  role: '',
  name: '',
  email: '',
  emailError: '',
  password: '',
  passwordVerify: '',
  passwordOld: '',
  address: '',
  postNumber: '',
  city: '',
  phone: '',
  birth: '',
  work: '',
  workDescription: '',
  contactPerson: '',
  workPhoneNumber: '',
  workAddress: '',
  goals: '',
  academy: '',
  education: '',
  businessID: '',
  businessIDError: '',
  editedCompanyName: '',
  companyName: null,
  työpaikkaohjaajat: [],
  firstName: '',
  lastName: '',
  työpaikkaohjaajaEmail: '',
  openNotificationModal: false,

  // Define setter functions to update state variables
  setRole: (role) => set({ role }),
  setName: (name) => set({ name }),
  setEmail: (email) => set({ email }),
  setEmailError: (value) => set(() => ({ emailError: value })),
  setPassword: (password) => set({ password }),
  setPasswordVerify: (passwordVerify) => set({ passwordVerify }),
  setPasswordOld: (passwordOld) => set({ passwordOld }),
  setAddress: (address) => set({ address }),
  setPostNumber: (postNumber) => set({ postNumber }),
  setCity: (city) => set({ city }),
  setPhone: (phone) => set({ phone }),
  setBirth: (birth) => set({ birth }),
  setWork: (work) => set({ work }),
  setWorkDescription: (workDescription) => set({ workDescription }),
  setContactPerson: (contactPerson) => set({ contactPerson }),
  setWorkPhoneNumber: (workPhoneNumber) => set({ workPhoneNumber }),
  setWorkAddress: (workAddress) => set({ workAddress }),
  setGoals: (goals) => set({ goals }),
  setAcademy: (academy) => set({ academy }),
  setEducation: (education) => set({ education }),
  setOpenNotificationModal: (openNotificationModal) =>
  set({ openNotificationModal }),
  setBusinessId: (value) => set(() => ({ businessID: value })),
  setBusinessIdError: (value) => set(() => ({ businessIDError: value })),
  setCompanyName: (value) => set(() => ({ companyName: value })),
  setEditedCompanyName: (value) => set(() => ({ editedCompanyName: value })),
  setTyöpaikkaohjaajat: (value) => set(() => ({ työpaikkaohjaajat: value })),
  setFirstName: (value) => set(() => ({ firstName: value })),
  setLastName: (value) => set(() => ({ lastName: value })),
  setTyöpaikkaohjaajaEmail: (value) => set(() => ({ työpaikkaohjaajaEmail: value })),
  // Define a resetForm function to reset all state variables to their initial values
  resetForm: () =>
    set({
      name: '',
      email: '',
      emailError: '',
      password: '',
      passwordVerify: '',
      address: '',
      postNumber: '',
      city: '',
      phone: '',
      birth: '',
      work: '',
      workDescription: '',
      contactPerson: '',
      workPhoneNumber: '',
      workAddress: '',
      goals: '',
      academy: '',
      education: '',
      businessID: '',
      businessIDError: '',
      firstName: '',
      lastName: '',
      työpaikkaohjaajaEmail: '',
    }),
}));

export default useStore;
