name: Pull Request Test

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Optional: Upload test artifacts if test results exist
      - name: Upload Test Results
        if: success() && always() # Only run if previous steps succeed
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: /coverage # Update path to actual test results

      # Optional: Post test results as a comment on the pull request if test results exist
      - name: Post Test Results
        if: success() && always() # Only run if previous steps succeed
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('/coverage', 'utf8');
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test Results:\n' + results
            });
